image: php
labels:
  - role=php
working_dir: /src
cap_drop:
  - ALL
cap_add:
  - CHOWN
volumes:
  - env-storage:/src/env:rw
environment:
  - STORAGE_HOST=$STORAGE_HOST
  - STORAGE_PORT=$STORAGE_PORT
  - PROJECT=$COMPOSE_PROJECT_NAME
  - PROJECT_ENV=$ENV
  - PROJECT_REV=$REVISION
