image: php
labels:
  - role=php
working_dir: /src
cap_drop:
  - ALL
cap_add:
  - CHOWN
volumes:
  - env-storage:/src/env:rw
environment:
  - ARDB_HOST=$ARDB_HOST
  - ARDB_PORT=$ARDB_PORT
  - PROJECT=$COMPOSE_PROJECT_NAME
  - PROJECT_ENV=$ENV
  - PROJECT_REV=$REVISION
